#!/usr/bin/env python

# mysql_install_db redirector

# Distributions of MySQL version 5.7.6 and above do not include the 
# file scripts/mysql_install_db, but instead include a binary 
# executable bin/mysql_install_db, that provides the same interface
# and features (with some caveats). 

import sys
import subprocess
import os.path

def clean_args(args):
  cleaned = []
  for arg in args:
    if arg == "--force":
      pass
    else:
      cleaned.append(arg)
  return cleaned

if __name__ == '__main__':
  this_script_pathname = sys.argv[0]
  print "this script is", this_script_pathname
  scripts_dir = os.path.dirname(this_script_pathname)
  dist_dir = os.path.dirname(scripts_dir)
  mysql_install_db_exec = os.path.join(dist_dir, 'bin', 'mysql_install_db')
  cleaned = clean_args(sys.argv[1:])
  print "calling", mysql_install_db_exec, "with arguments", cleaned
  args = [mysql_install_db_exec] + cleaned
  returncode = subprocess.call(args)
  print mysql_install_db_exec, "exited with code", returncode
  exit(returncode)
